### ISSUE TITLE
App\Http\Controllers\Spatie\WebhookClient\Http\Controllers\WebhookController was not found

### ISSUE THREAD

**Issue by kartman5** [spatie/laravel-webhook-client#138]
Hi,

After upgrading this package to the 3.1.0 package not working properly.

This throw `WebhookController was not found` error.

How can I resolve this issue?

Thanks.

**Comment by freekmurze** [comment]
That namespace is wrong. Use`\Spatie\WebhookClient\Http\Controllers\WebhookController`

**Comment by kartman5** [comment]
I know it's a namespace error, but this error comes after updating in laravel 9.

**Comment by kartman5** [comment]
![image](https://user-images.githubusercontent.com/68532634/161037834-151fb1a3-db94-450f-bd56-c81f2a5a5c78.png)

Above error message comes when doing a composer update and all other PHP artisan commands.

**Comment by ankurk91** [comment]
The error is coming because of this line

https://github.com/spatie/laravel-webhook-client/blob/0e078c1af500b573e5693faf5d480b1a88fc1aad/src/WebhookClientServiceProvider.php#L25


Package should define controller like

```php
return Route::post($url, '\Spatie\WebhookClient\Http\Controllers\WebhookController')->name("webhook-client-{$name}");
```

otherwise laravel will unable to find the controller when the macro is inside a group like
```php
Route::group(['namespace'=> 'MyPath\Folder'], function() {
    Route::webhook("my-webhhok");
});
```

@freekmurze Would you accept a PR ?

Similar PR was send https://github.com/spatie/laravel-stripe-webhooks/pull/100

**Comment by freekmurze** [comment]
@ankurk91 Yup, send a PR 👍
