### ISSUE TITLE
Customize response

### ISSUE THREAD

**Issue by whoami213** [spatie/laravel-webhook-client#84]
Hi, it is possible to customize the error response to invalid signature? Instead of 500 I will customize it to 401, like for Xero accounting app.

**Comment by freekmurze** [comment]
You could listen for the `InvalidSignatureEvent` and throw the exception you want there.

**Comment by kasperwandahl** [comment]
Hi @freekmurze I was just looking into this exact thing as a company I'm working with received the 500 Internal Server Error and pointed their fingers at me, when the issue was in their side not sending the signature. I think a 401 Unauthorized is a better response code as it's their input which fails to pass validation. Would you be willing to consider this change?

**Comment by freekmurze** [comment]
Send a PR with tests, and I'll consider merging it in.
